### ISSUE TITLE
[Enhancement] - Translate Docs to pt-BR

### ISSUE THREAD

**Issue by guastallaigor** [vuetifyjs/electron#3]
### This is an enhancement issue to ask if you are interested in translate the docs to pt-BR (Brazilian Portuguese). 

I'm starting now and will try my best to translate all the vuetify docs (starting by electron) the best way I can in my free time.
I think this is important because here in Brazil Vuejs is growing a lot and Vuetify is growing with it. In the company I'm working now I work, most of us there work with Vuejs and Vuetify everyday, but unfortunately not all of us have a great english knowledge.

Full disclosure, mine is not also the best, but I'm consulting with a few of my work colleagues and I think it's looking good.
If you are not interested, that's ok, but please just let me know.

**Comment by nekosaur** [comment]
I would recommend you start translating the vuetify docs themselves. @peluprvi already started the process here https://github.com/vuetifyjs/vuetifyjs.com/pull/160 so you could possibly start from there. Although things might have changed since then.

**Comment by peluprvi** [comment]
@guastallaigor Since I'm moving, I'm without time to make progress on this translations (and I'm also too slow on it). Your help will be awesome!
I did some translations that you can use in your code to avoid rework. We can also work together in some branch.
You can find me on [Vuetify community](https://community.vuetifyjs.com/). I can find you if you post in the i18n channel that you are helping translate docs to pt-BR.

**Comment by guastallaigor** [comment]
We started working together on [peluprvi's branch](https://github.com/vuetifyjs/vuetifyjs.com/tree/translation-pt-BR). If anyone else wants to help too, just contact any of us to make sure we organize it and don't end up translating the same file more than once. I'm closing this issue.
